//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DullStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("GioHang")]
    public partial class GioHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GioHang()
        {
            this.ChiTietGioHang = new HashSet<ChiTietGioHang>();
        }

        [Key]
        [Display(Name = "Mã hóa đơn")]
        public int ma { get; set; }

        [Display(Name = "Mã khách hàng")]
        public Nullable<int> makhachhang { get; set; }

        [Display(Name = "Ngày đặt hàng")]
        [Column(TypeName = "date")]
        public Nullable<System.DateTime> ngaydathang { get; set; }

        [Display(Name = "Ngày giao hàng")]
        [Column(TypeName = "date")]
        public Nullable<System.DateTime> ngaygiaohang { get; set; }

        [Display(Name = "Tình trạng giao hàng")]
        [StringLength(50)]
        public string tinhtranggiaohang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
